- name: demo vars from file
  hosts: localhost
  vars_files:
    test.yml
  tasks:
    - name: PRINT URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: demo on roles
  hosts: localhost
  tasks:
  roles:
    - sample
    - mongo

- name: demo on integers
  hosts: localhost
  tasks:
    - name: print addition
      anisible.builtin.debug:
        msg: "hello addition"

