- name: demo vars from file
  hosts: localhost
  vars_files:
    test.yml
  tasks:
    - name: PRINT URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: demo on roles
  hosts: localhost
  tasks:
  roles:
    - sample
    - mongo

- name: demo on play
  hosts: localhost
  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: "hello addition"

- name: demo on package
  hosts: localhost
  tasks:
  roles:
    - roles_1
        
- name: Download mongodb repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: start mongodb service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Replace a localhost entry with our own
  ansible.builtin.lineinfile:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    line: '0.0.0.0'


