- name: demo vars from file
  hosts: localhost
  vars_files:
    test.yml
  tasks:
    - name: PRINT URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: demo on roles
  hosts: localhost
  tasks:
  roles:
    - sample
    - mongo

- name: demo on play
  hosts: localhost
  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: "hello addition"

- name: demo on cli
  hosts: localhost
  tasks:
    - name: print cli
      ansible.builtin.debug:
        msg: "{{ CLI }}"

