- name: demo on loop
  hosts: localhost
  tasks:
    - name: loop on lists
      ansible.builtin.debug:
        msg: " Fruit name - {{ item }}"
      loop:
        - orange
        - apple


- name: demo on map loop
  hosts: localhost
  tasks:
    - name: loop on maps
      ansible.builtin.debug:
        msg: " Fruit name - {{ item.name }} count - {{ item.count }}"
      loop:
        - { name:'orange' , count: '100' }
        - { name:'apple' , count: '50' }