- name: just a demo play
  hosts: localhost
  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: welcome to ansible


- name: demo on vars
  hosts: localhost
  tasks:
    - name: print hello
      ansible.builtin.debug:

- name: demo on vars play level
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: demo on vars task level
  hosts: localhost
  tasks:
    - name: print URL
      vars:
        URL: play.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: demo on vars from file on play level
  hosts: localhost
  tasks:
   - name: print URL
     ansible.builtin.debug:
        msg: URL = {{ URL }}
     vars_files:
        - demo-vars.yml