- name: just a demo play
  hosts: localhost
  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: welcome to ansible


- name: demo on vars
  hosts: localhost
  tasks:
    - name: print hello
      ansible.builtin.debug:

- name: demo on vars
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}