- name: just a demo play
  hosts: localhost
  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: welcome to ansible


- name: demo on vars
  hosts: localhost
  tasks:
    - name: print hello
      ansible.builtin.debug: