- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Include Download App content  from common
  ansible.builtin.include_role:
    name: common
    tasks_from: download.yml

- name: Copy roboshop configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start nginx service
  ansible.builtin.systemd:
     name: nginx
     state: restarted
     enabled: yes



  #mv frontend-main/static/* . &>>{LOG}
  # mv frontend-main/localhost.conf /etc/nginx/default.d/roboshop.conf &>>{LOG}

  #PRINT "Update RoboShop Configuration"
  #sed -i -e '/catalogue/ s/localhost/dev-catalogue.mydevops410.online/' -e '/user/ s/localhost/dev-user.mydevops410.online/' -e '/cart/ s/localhost/dev-cart.mydevops410.online/' -e '/shipping/ s/localhost/dev-shipping.mydevops410.online/' -e '/payment/ s/localhost/dev-payment.mydevops410.online/' /etc/nginx/default.d/roboshop.conf
  #STAT $?

