- name: Download mongodb repo file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: start mongodb service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes