- name: download mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: start mongodb service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: replace listen update file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download APP content and extract it
  ansible.builtin.unarchive:
    src: ""https://github.com/roboshop-devops-project/{{ COMPONENT }}}/archive/main.zip""
    dest: "/tmp"
    remote_src: yes

- name: load schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
    loop:
      - catalogue
      - users
