- name: setting root password
  ansible.builtin.set_fact:
    ROOT_PASSWORD: "{{ lookup('aws_ssm', 'param.{{ENV}}.mysql.ROOT_PASSWORD', region='us-east-1' ) }}"

- name: copy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: disable mysql 8 version repo
  ansible.builtin.shell: dnf module disable mysql -y

- name: install mysql server
  ansible.builtin.yum:
    name:
    - mysql-community-server
    - python3-PyMySQL
    state: installed

- name: start mysql
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes
    state: restarted

- name: Get MySQL version
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ROOT_PASSWORD}}"
    filter: version
    ignore_errors: yes
    register: out

- name: debug
  debug:
    msg: {{OUT}}



