- name: Add application user
  when: APP_USER is defined
  ansible.builtin.user:
    name: " {{ APP_USER }}"

- name: Download APP content
  ansible.builtin.get_url:
    url: "https://github.com/Aleem410/frontend.git/{{ COMPONENT }}/archive/main.zip"
    dest: /tmp/{{ COMPONENT }}.zip

- name: Remove previous version of App
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent

- name: Download APP content and extract it
  ansible.builtin.unarchive:
    src: "https://github.com/Aleem410/frontend.git/{{ COMPONENT }}/archive/main.zip"
    dest: "/tmp"
    remote_src: yes

- name: copy Extract content to APP location
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main/
    dest: "{{ APP_LOC }}/"
    remote_src: yes

