- name: configure nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include Download App content  from common
  ansible.builtin.include_role:
    name: common
    tasks_from: download.yml

- name: Install nodejs dependencis.
  community.general.npm:
    path: "{{ APP_LOC }}"

- name: LOAD schema
  when: LOAD_SCHEMA
  ansible.builtin.include_role:
    name: common
    tasks_from: "{{ DB_TYPE }}"

- name: Include systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd.yml